In [ ]:
#df = pd.read_csv("sentiment140.csv", encoding = "cp1252", header=None)
#df.columns =['score', 'id', 'time', 'query', 'user_name', 'comment']
#df = df.drop(['id', 'time', 'query', 'user_name'], axis=1)
#df.comment.isnull().sum()

#score_cnt = df.groupby("score")["comment"].count()/len(df)
# The score has only 0 and 4, so change 4 into 1.
#df.loc[df.score == 4, 'score'] = 1
#score_cnt_new = df.groupby("score")["comment"].count()/len(df)

#from nltk import word_tokenize

# Tokenize each item in the review column
#word_tokens = [word_tokenize(com) for com in df.comment]

# Create an empty list to store the length of the reviews
#len_tokens = []

# Iterate over the word_tokens list and determine the length of each item
#for i in range(len(word_tokens)):
     #len_tokens.append(len(word_tokens[i]))

# Create a new feature for the lengh of each review
#df['n_words'] = len_tokens
#df.to_csv("sentiment140_new.csv", encoding="utf-8")

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/drive/MyDrive/Redback_A/sentiment140_new.csv")
df = df.drop("Unnamed: 0", axis=1)
df.head()

   score                                            comment  n_words
0      0  @switchfoot http://twitpic.com/2y1zl - Awww, t...       27
1      0  is upset that he can't update his Facebook by ...       25
2      0  @Kenichan I dived many times for the ball. Man...       21
3      0    my whole body feels itchy and like its on fire        10
4      0  @nationwideclass no, it's not behaving at all....       30

In [ ]:
# Import the TfidfVectorizer and default list of English stop words
from sklearn.feature_extraction.text import TfidfVectorizer, ENGLISH_STOP_WORDS
from nltk import word_tokenize

# Build the vectorizer
vect = TfidfVectorizer(stop_words=list(ENGLISH_STOP_WORDS), 
                       ngram_range=(1, 2), 
                       max_features=50, 
                       token_pattern=r'\b[^\d\W][^\d\W]+\b').fit(df.comment)
# Create sparse matrix from the vectorizer
X = vect.transform(df.comment)

# Create a DataFrame
reviews_transformed = pd.DataFrame(X.toarray(), columns=vect.get_feature_names_out())

In [ ]:
reviews_transformed.head()

,amp,bad,com,come,day,did,don,feel,fun,going,...,time,today,tomorrow,tonight,twitter,ve,want,way,wish,work
0,0.0,0.0,0.526931,0.0,0.471249,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df = df.drop('comment', axis=1)
df.head()

   score  n_words
0      0       27
1      0       25
2      0       21
3      0       10
4      0       30

In [ ]:
reviews_transformed = reviews_transformed.merge(df, left_index=True, right_index=True)

In [ ]:
reviews_transformed.columns

Index(['amp', 'bad', 'com', 'come', 'day', 'did', 'don', 'feel', 'fun',
       'going', 'good', 'got', 'great', 'haha', 'happy', 'home', 'hope',
       'http', 'im', 'just', 'know', 'like', 'll', 'lol', 'love', 'make',
       'miss', 'morning', 'need', 'new', 'night', 'oh', 'quot', 'really',
       'right', 'sad', 'sleep', 'sorry', 'thanks', 'think', 'time', 'today',
       'tomorrow', 'tonight', 'twitter', 've', 'want', 'way', 'wish', 'work',
       'score', 'n_words'],
      dtype='object')

In [ ]:
len(reviews_transformed.index)

1600000

In [ ]:
reviews_transformed.head()

,amp,bad,com,come,day,did,don,feel,fun,going,...,tomorrow,tonight,twitter,ve,want,way,wish,work,score,n_words
0,0.0,0.0,0.526931,0.0,0.471249,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,27
1,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,25
2,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,21
3,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,10
4,0.0,0.0,0.000000,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0,30

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score

# Define X and y
y = reviews_transformed.score
X = reviews_transformed.drop('score', axis=1)

# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, stratify=y, test_size=0.3, random_state=456)

Use a variant of PCA called non-negative matrix factorization (NMF) to enforce non-negativity in the transformed data. NMF is a matrix factorization technique that decomposes a non-negative matrix into two non-negative matrices, which can be interpreted as basis vectors and coefficients, respectively.

In [ ]:
# Apply NMF for feature reduction
from sklearn.decomposition import NMF
nmf = NMF(n_components=20, init='nndsvd')
X_train_nmf = nmf.fit_transform(X_train)
X_test_nmf = nmf.transform(X_test)

/usr/local/lib/python3.9/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(

In [ ]:
(X_test_nmf < 0).any().any()

False

In [ ]:
# Import the Multinomial Naive Bayes classifier
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, confusion_matrix

# Create a Multinomial Naive Bayes classifier: nb_classifier
nb_classifier = MultinomialNB()
scores = cross_val_score(nb_classifier, X_train_nmf, y_train, cv=3)

# Evaluate the performance of the model using cross-validation
print('Cross-validation scores: {}'.format(scores))
print('Average cross-validation score: {:.2f}'.format(scores.mean()))

Cross-validation scores: [0.58486235 0.58408445 0.58366659]
Average cross-validation score: 0.58

In [ ]:
# Use grid_search to find the optimal C
from sklearn.model_selection import GridSearchCV
import numpy as np

# Define the parameter grid for the SVM model
param_grid = {'alpha': list(np.arange(0, 1, .2))}

# Define the MultinomialNB model 
nb_classifier = MultinomialNB()

# Perform grid search cross-validation to find the optimal value of alpha
grid_search = GridSearchCV(estimator=nb_classifier, param_grid=param_grid, cv=5)
grid_search.fit(X_train_nmf, y_train)

# Print the results
print("Best alpha:", grid_search.best_params_['alpha'])
print("Best score:", grid_search.best_score_)

/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:629: FutureWarning: The default value for `force_alpha` will change to `True` in 1.4. To suppress this warning, manually set the value of `force_alpha`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/naive_bayes.py:635: UserWarning: alpha too small will result in numeric errors, setting alpha = 1.0e-10. Use `force_alpha=True` to keep alpha unchanged.
  warnings.warn(

Best alpha: 0.6000000000000001
Best score: 0.5841535714285715

In [ ]:
# Use the best alpha value
nb_classifier = MultinomialNB(alpha=0.6)

# Fit the classifier to the training data
nb_classifier.fit(X_train_nmf, y_train)

# Create the predicted tags: pred
pred = nb_classifier.predict(X_test_nmf)

# Print accuracy score and confusion matrix on test set
print('Accuracy on the test set: ', accuracy_score(y_test, pred))
print(confusion_matrix(y_test, pred)/len(y_test))

Accuracy on the test set:  0.58363125
[[0.41435833 0.08564167]
 [0.33072708 0.16927292]]

In [ ]:
# Get the class labels: class_labels
class_labels = nb_classifier.classes_

# Extract the features: feature_names
feature_names = vect.get_feature_names_out()

# Zip the feature names together with the coefficient array and sort by weights: feat_with_weights
# feat_with_weights = sorted(zip(nb_classifier.coef_[0], feature_names))
feat_with_weights = sorted(zip(nb_classifier.feature_log_prob_[1] - nb_classifier.feature_log_prob_[0], feature_names))

# Print the first class label and the top 5 feat_with_weights entries
print(class_labels[0], feat_with_weights[:5])

# Print the second class label and the bottom 5 feat_with_weights entries
print(class_labels[1], feat_with_weights[-5:])

0 [(-0.8729647876498836, 'going'), (-0.8675032578014976, 'im'), (-0.564102985213685, 'http'), (-0.4341183265241515, 'home'), (-0.26146860034106645, 'feel')]
1 [(0.5502237779750399, 'haha'), (0.6874064729705598, 'com'), (0.71827760603471, 'come'), (1.0874375820133482, 'don'), (1.8447409318610166, 'happy')]